2020-12-17 01:28:32,959 INFO    MainThread:605917 [wandb_setup.py:_flush():70] setting env: {}
2020-12-17 01:28:32,959 INFO    MainThread:605917 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2020-12-17 01:28:32,959 INFO    MainThread:605917 [wandb_setup.py:_flush():70] setting login settings: {}
2020-12-17 01:28:32,959 INFO    MainThread:605917 [wandb_init.py:_log_setup():303] Logging user logs to /home/chaoyanghe/sourcecode/MiLeNAS/wandb/run-20201217_012832-3cbup2g3/logs/debug.log
2020-12-17 01:28:32,959 INFO    MainThread:605917 [wandb_init.py:_log_setup():304] Logging internal logs to /home/chaoyanghe/sourcecode/MiLeNAS/wandb/run-20201217_012832-3cbup2g3/logs/debug-internal.log
2020-12-17 01:28:33,808 INFO    MainThread:605917 [wandb_run.py:_console_start():1237] atexit reg
2020-12-17 01:28:33,809 INFO    MainThread:605917 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.REDIRECT
2020-12-17 01:28:33,810 INFO    MainThread:605917 [wandb_run.py:_redirect():1107] Redirecting console.
2020-12-17 01:28:33,810 INFO    MainThread:605917 [redirect.py:install():204] install start
2020-12-17 01:28:33,811 INFO    MainThread:605917 [redirect.py:install():219] install stop
2020-12-17 01:28:33,811 INFO    MainThread:605917 [redirect.py:install():204] install start
2020-12-17 01:28:33,811 INFO    MainThread:605917 [redirect.py:install():219] install stop
2020-12-17 01:28:33,811 INFO    MainThread:605917 [wandb_run.py:_redirect():1151] Redirects installed.
2020-12-17 01:28:38,076 INFO    MainThread:605917 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 1
2020-12-17 01:28:38,076 INFO    MainThread:605917 [wandb_run.py:_restore():1179] restore
2020-12-17 01:28:38,076 INFO    MainThread:605917 [redirect.py:uninstall():223] uninstall start
2020-12-17 01:28:38,077 INFO    MainThread:605917 [redirect.py:_stop():278] _stop: stdout
2020-12-17 01:28:38,077 INFO    MainThread:605917 [redirect.py:_stop():284] _stop closed: stdout
2020-12-17 01:28:38,077 INFO    stdout    :605917 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2020-12-17 01:28:38,078 INFO    stdout    :605917 [redirect.py:_pipe_relay():136] relay done done: stdout
2020-12-17 01:28:38,078 INFO    MainThread:605917 [redirect.py:_stop():290] _stop joined: stdout
2020-12-17 01:28:38,078 INFO    MainThread:605917 [redirect.py:_stop():292] _stop rd closed: stdout
2020-12-17 01:28:38,078 INFO    MainThread:605917 [redirect.py:uninstall():227] uninstall done
2020-12-17 01:28:38,078 INFO    MainThread:605917 [redirect.py:uninstall():223] uninstall start
2020-12-17 01:28:38,078 INFO    MainThread:605917 [redirect.py:_stop():278] _stop: stderr
2020-12-17 01:28:38,079 INFO    MainThread:605917 [redirect.py:_stop():284] _stop closed: stderr
2020-12-17 01:28:38,079 INFO    stderr    :605917 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2020-12-17 01:28:38,079 INFO    stderr    :605917 [redirect.py:_pipe_relay():136] relay done done: stderr
2020-12-17 01:28:38,079 INFO    MainThread:605917 [redirect.py:_stop():290] _stop joined: stderr
2020-12-17 01:28:38,079 INFO    MainThread:605917 [redirect.py:_stop():292] _stop rd closed: stderr
2020-12-17 01:28:38,079 INFO    MainThread:605917 [redirect.py:uninstall():227] uninstall done
2020-12-17 01:28:38,083 INFO    MainThread:605917 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "62467a7628a842d38927f1d35c4960b0"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 1430
      total_bytes: 1430
    }
  }
}

2020-12-17 01:28:40,089 INFO    MainThread:605917 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "dbd1b710a82c46c7ac1910f16b913b6c"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 8449
      total_bytes: 8449
    }
  }
}

2020-12-17 01:28:41,173 INFO    MainThread:605917 [wandb_run.py:_show_files():1536] logging synced files
2020-12-17 01:28:41,174 INFO    MainThread:605917 [internal.py:handle_exit():138] Internal process exited
